// <auto-generated />
using System;
using Api.ApiDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.ApiDbContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260715213009_AddPhotoEmployee")]
    partial class AddPhotoEmployee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "US",
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Code = "CA",
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 3,
                            Code = "UK",
                            Name = "United Kingdom"
                        });
                });

            modelBuilder.Entity("Api.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("FotoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = new Guid("67f3b154-5ef9-4acd-ae15-6e04b6db9741"),
                            Active = true,
                            CountryId = 1,
                            Name = "John Doe",
                            Position = "Software Engineer"
                        },
                        new
                        {
                            Id = new Guid("67f3b154-5ef9-4acd-ae15-6e04b6db9742"),
                            Active = true,
                            CountryId = 2,
                            Name = "Jane Smith",
                            Position = "Project Manager"
                        },
                        new
                        {
                            Id = new Guid("67f3b154-5ef9-4acd-ae15-6e04b6db9743"),
                            Active = false,
                            CountryId = 3,
                            Name = "Bob Johnson",
                            Position = "Designer"
                        },
                        new
                        {
                            Id = new Guid("67f3b154-5ef9-4acd-ae15-6e04b6db9744"),
                            Active = false,
                            CountryId = 3,
                            Name = "Bob Johnson",
                            Position = "Designer"
                        });
                });

            modelBuilder.Entity("Api.Models.Employee", b =>
                {
                    b.HasOne("Api.Models.Country", "Country")
                        .WithMany("Employees")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Api.Models.Country", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
